@PORT=4000

GET http://localhost:{{PORT}}/api/workouts

###
GET http://localhost:{{PORT}}/api/workouts/:id

###
GET http://localhost:{{PORT}}/api/workouts/6804ec3f64af64bf28e15819

###POST 创建一条 workout记录
POST http://localhost:{{PORT}}/api/workouts
Content-Type: application/json

{
  "title": "Push Ups",
  "reps": 10,
  "load": 20
}

###
POST http://localhost:{{PORT}}/api/workouts
Content-Type: application/json

{
  "title": "Squats",
  "reps": 15,
  "load": 30
}

###
DELETE http://localhost:{{PORT}}/api/workouts/:id

###
PATCH http://localhost:{{PORT}}/api/workouts/:id